// let a = 3;

// try {
//   console.log(('a', a));
// } catch (err) {
//   console.log(('â€˜let must be declared', err)); // (3)
// }
